dct = {
    "Agriculture, General.": "0100",
"Agricultural Business and Management.": "0101",
"Animal Sciences.": "0109",
"Food Science and Technology.": "0110",
"Food Science and Technology.": "0110",
"Food Science and Technology.": "0110",
"Plant Sciences.": "0111",
"Agriculture, Agriculture Operations, and Related Sciences, Other.": "0199",
"Agriculture, Agriculture Operations, and Related Sciences, Other.": "0199",
"Agriculture, Agriculture Operations, and Related Sciences, Other.": "0199",
"Forestry.": "0305",
"City/Urban, Community and Regional Planning.": "0403",
"City/Urban, Community and Regional Planning.": "0403",
"Ethnic, Cultural Minority, Gender, and Group Studies.": "0502",
"Communication and Media Studies.": "0901",
"Audiovisual Communications Technologies/Technicians.": "1002",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Education, General.": "1301",
"Education, General.": "1301",
"Educational Administration and Supervision.": "1304",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Civil Engineering.": "1408",
"Electrical, Electronics and Communications Engineering.": "1410",
"Mechanical Engineering.": "1419",
"Engineering, Other.": "1499",
"Electrical Engineering Technologies/Technicians.": "1503",
"Industrial Production Technologies/Technicians.": "1506",
"Mechanical Engineering Related Technologies/Technicians.": "1508",
"Construction Engineering Technologies.": "1510",
"Family and Consumer Sciences/Human Sciences, General.": "1901",
"Family and Consumer Sciences/Human Sciences, General.": "1901",
"English Language and Literature, General.": "2301",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Mathematics.": "2701",
"Health and Physical Education/Fitness.": "3105",
"Health and Physical Education/Fitness.": "3105",
"Chemistry.": "4005",
"Physics.": "4008",
"Physics.": "4008",
"Physics.": "4008",
"Psychology, General.": "4201",
"Clinical, Counseling and Applied Psychology.": "4228",
"Criminal Justice and Corrections.": "4301",
"Social Work.": "4407",
"Social Work.": "4407",
"Political Science and Government.": "4510",
"Sociology.": "4511",
"Fine and Studio Arts.": "5007",
"Music.": "5009",
"Communication Disorders Sciences and Services.": "5102",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Entrepreneurial and Small Business Operations.": "5207",
"Finance and Financial Management Services.": "5208",
"Marketing.": "5214",
"Ethnic, Cultural Minority, Gender, and Group Studies.": "0502",
"Communication and Media Studies.": "0901",
"Communication and Media Studies.": "0901",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Information Science/Studies.": "1104",
"Computer/Information Technology Administration and Management.": "1110",
"Computer/Information Technology Administration and Management.": "1110",
"Education, General.": "1301",
"Education, General.": "1301",
"Curriculum and Instruction.": "1303",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational Assessment, Evaluation, and Research.": "1306",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Student Counseling and Personnel Services.": "1311",
"Student Counseling and Personnel Services.": "1311",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teaching English or French as a Second or Foreign Language.": "1314",
"Teaching English or French as a Second or Foreign Language.": "1314",
"Engineering, General.": "1401",
"Engineering, General.": "1401",
"Biomedical/Medical Engineering.": "1405",
"Biomedical/Medical Engineering.": "1405",
"Biomedical/Medical Engineering.": "1405",
"Civil Engineering.": "1408",
"Civil Engineering.": "1408",
"Civil Engineering.": "1408",
"Computer Engineering.": "1409",
"Electrical, Electronics and Communications Engineering.": "1410",
"Electrical, Electronics and Communications Engineering.": "1410",
"Materials Engineering": "1418",
"Materials Engineering": "1418",
"Materials Engineering": "1418",
"Mechanical Engineering.": "1419",
"Mechanical Engineering.": "1419",
"Construction Engineering.": "1433",
"Electrical and Computer Engineering.": "1447",
"Engineering, Other.": "1499",
"Engineering, Other.": "1499",
"Linguistic, Comparative, and Related Language Studies and Services.": "1601",
"Romance Languages, Literatures, and Linguistics.": "1609",
"Romance Languages, Literatures, and Linguistics.": "1609",
"English Language and Literature, General.": "2301",
"English Language and Literature, General.": "2301",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Biochemistry, Biophysics and Molecular Biology.": "2602",
"Cell/Cellular Biology and Anatomical Sciences.": "2604",
"Microbiological Sciences and Immunology.": "2605",
"Microbiological Sciences and Immunology.": "2605",
"Genetics.": "2608",
"Genetics.": "2608",
"Physiology, Pathology and Related Sciences.": "2609",
"Physiology, Pathology and Related Sciences.": "2609",
"Pharmacology and Toxicology.": "2610",
"Biomathematics, Bioinformatics, and Computational Biology.": "2611",
"Biomathematics, Bioinformatics, and Computational Biology.": "2611",
"Biotechnology.": "2612",
"Biotechnology.": "2612",
"Ecology, Evolution, Systematics, and Population Biology.": "2613",
"Molecular Medicine.": "2614",
"Neurobiology and Neurosciences.": "2615",
"Neurobiology and Neurosciences.": "2615",
"Biological and Biomedical Sciences, Other.": "2699",
"Biological and Biomedical Sciences, Other.": "2699",
"Mathematics.": "2701",
"Mathematics.": "2701",
"Applied Mathematics.": "2703",
"Systems Science and Theory.": "3006",
"Systems Science and Theory.": "3006",
"Nutrition Sciences.": "3019",
"Nutrition Sciences.": "3019",
"Intercultural/Multicultural and Diversity Studies.": "3023",
"Data Science.": "3070",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Health and Physical Education/Fitness.": "3105",
"Philosophy.": "3801",
"Chemistry.": "4005",
"Chemistry.": "4005",
"Chemistry.": "4005",
"Physics.": "4008",
"Physics.": "4008",
"Physics.": "4008",
"Science Technologies/Technicians, General.": "4100",
"Psychology, General.": "4201",
"Psychology, General.": "4201",
"Psychology, General.": "4201",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Security Science and Technology.": "4304",
"Security Science and Technology.": "4304",
"Public Administration.": "4404",
"Public Administration.": "4404",
"Social Work.": "4407",
"Anthropology.": "4502",
"Anthropology.": "4502",
"Political Science and Government.": "4510",
"Sociology.": "4511",
"Sociology.": "4511",
"Sociology.": "4511",
"Social Sciences, Other.": "4599",
"Drama/Theatre Arts and Stagecraft.": "5005",
"Fine and Studio Arts.": "5007",
"Fine and Studio Arts.": "5007",
"Music.": "5009",
"Health Services/Allied Health/Health Sciences, General.": "5100",
"Health Services/Allied Health/Health Sciences, General.": "5100",
"Dentistry.": "5104",
"Dentistry.": "5104",
"Advanced/Graduate Dentistry and Oral Sciences.": "5105",
"Advanced/Graduate Dentistry and Oral Sciences.": "5105",
"Dental Support Services and Allied Professions.": "5106",
"Health and Medical Administrative Services.": "5107",
"Health and Medical Administrative Services.": "5107",
"Health and Medical Administrative Services.": "5107",
"Health and Medical Administrative Services.": "5107",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Clinical/Medical Laboratory Science/Research and Allied Professions.": "5110",
"Clinical/Medical Laboratory Science/Research and Allied Professions.": "5110",
"Medicine.": "5112",
"Mental and Social Health Services and Allied Professions.": "5115",
"Optometry.": "5117",
"Public Health.": "5122",
"Public Health.": "5122",
"Public Health.": "5122",
"Public Health.": "5122",
"Public Health.": "5122",
"Public Health.": "5122",
"Rehabilitation and Therapeutic Professions.": "5123",
"Rehabilitation and Therapeutic Professions.": "5123",
"Rehabilitation and Therapeutic Professions.": "5123",
"Rehabilitation and Therapeutic Professions.": "5123",
"Dietetics and Clinical Nutrition Services.": "5131",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Business/Managerial Economics.": "5206",
"Finance and Financial Management Services.": "5208",
"Human Resources Management and Services.": "5210",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Marketing.": "5214",
"Marketing.": "5214",
"General Sales, Merchandising and Related Marketing Operations.": "5218",
"General Sales, Merchandising and Related Marketing Operations.": "5218",
"History.": "5401",
"History.": "5401",
"Educational Administration and Supervision.": "1304",
"Human Development, Family Studies, and Related Services.": "1907",
"Human Development, Family Studies, and Related Services.": "1907",
"Human Development, Family Studies, and Related Services.": "1907",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Multi-/Interdisciplinary Studies, General.": "3000",
"Religion/Religious Studies.": "3802",
"Bible/Biblical Studies.": "3902",
"Bible/Biblical Studies.": "3902",
"Bible/Biblical Studies.": "3902",
"Bible/Biblical Studies.": "3902",
"Theological and Ministerial Studies.": "3906",
"Theological and Ministerial Studies.": "3906",
"Pastoral Counseling and Specialized Ministries.": "3907",
"Pastoral Counseling and Specialized Ministries.": "3907",
"Pastoral Counseling and Specialized Ministries.": "3907",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Mental and Social Health Services and Allied Professions.": "5115",
"Mental and Social Health Services and Allied Professions.": "5115",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business/Corporate Communications.": "5205",
"Human Resources Management and Services.": "5210",
"Human Resources Management and Services.": "5210",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Communication and Media Studies.": "0901",
"Communication and Media Studies.": "0901",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Computer Software and Media Applications.": "1108",
"Computer/Information Technology Administration and Management.": "1110",
"Computer/Information Technology Administration and Management.": "1110",
"Computer/Information Technology Administration and Management.": "1110",
"Education, General.": "1301",
"Education, General.": "1301",
"Special Education and Teaching.": "1310",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teaching English or French as a Second or Foreign Language.": "1314",
"Teaching English or French as a Second or Foreign Language.": "1314",
"Engineering, General.": "1401",
"Engineering, General.": "1401",
"Aerospace, Aeronautical and Astronautical Engineering.": "1402",
"Aerospace, Aeronautical and Astronautical Engineering.": "1402",
"Aerospace, Aeronautical and Astronautical Engineering.": "1402",
"Chemical Engineering.": "1407",
"Chemical Engineering.": "1407",
"Civil Engineering.": "1408",
"Civil Engineering.": "1408",
"Civil Engineering.": "1408",
"Computer Engineering.": "1409",
"Computer Engineering.": "1409",
"Computer Engineering.": "1409",
"Computer Engineering.": "1409",
"Computer Engineering.": "1409",
"Electrical, Electronics and Communications Engineering.": "1410",
"Electrical, Electronics and Communications Engineering.": "1410",
"Electrical, Electronics and Communications Engineering.": "1410",
"Mechanical Engineering.": "1419",
"Mechanical Engineering.": "1419",
"Mechanical Engineering.": "1419",
"Industrial Engineering.": "1435",
"Industrial Engineering.": "1435",
"Industrial Engineering.": "1435",
"Engineering, Other.": "1499",
"Engineering, Other.": "1499",
"Engineering, Other.": "1499",
"Linguistic, Comparative, and Related Language Studies and Services.": "1601",
"Linguistic, Comparative, and Related Language Studies and Services.": "1601",
"English Language and Literature, General.": "2301",
"English Language and Literature, General.": "2301",
"Rhetoric and Composition/Writing Studies.": "2313",
"Rhetoric and Composition/Writing Studies.": "2313",
"Rhetoric and Composition/Writing Studies.": "2313",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Biotechnology.": "2612",
"Mathematics.": "2701",
"Mathematics.": "2701",
"Applied Mathematics.": "2703",
"Biological and Physical Sciences.": "3001",
"Science, Technology and Society.": "3015",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Health and Physical Education/Fitness.": "3105",
"Philosophy.": "3801",
"Atmospheric Sciences and Meteorology.": "4004",
"Atmospheric Sciences and Meteorology.": "4004",
"Chemistry.": "4005",
"Chemistry.": "4005",
"Physics.": "4008",
"Physics.": "4008",
"Physics.": "4008",
"Materials Sciences.": "4010",
"Physical Sciences, Other.": "4099",
"Physical Sciences, Other.": "4099",
"Physical Sciences, Other.": "4099",
"Psychology, General.": "4201",
"Psychology, General.": "4201",
"Public Administration.": "4404",
"International Relations and National Security Studies.": "4509",
"Political Science and Government.": "4510",
"Political Science and Government.": "4510",
"Sociology.": "4511",
"Drama/Theatre Arts and Stagecraft.": "5005",
"Fine and Studio Arts.": "5007",
"Music.": "5009",
"Bioethics/Medical Ethics.": "5132",
"Bioethics/Medical Ethics.": "5132",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Business/Managerial Economics.": "5206",
"Finance and Financial Management Services.": "5208",
"Human Resources Management and Services.": "5210",
"Human Resources Management and Services.": "5210",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Management Sciences and Quantitative Methods.": "5213",
"Management Sciences and Quantitative Methods.": "5213",
"Management Sciences and Quantitative Methods.": "5213",
"Marketing.": "5214",
"History.": "5401",
"History.": "5401",
"History.": "5401",
"History.": "5401",
"Communication and Media Studies.": "0901",
"Information Science/Studies.": "1104",
"Computer Science.": "1107",
"Computer/Information Technology Administration and Management.": "1110",
"Education, General.": "1301",
"Education, General.": "1301",
"Education, General.": "1301",
"Education, General.": "1301",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational/Instructional Media Design.": "1305",
"Educational/Instructional Media Design.": "1305",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Student Counseling and Personnel Services.": "1311",
"Student Counseling and Personnel Services.": "1311",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Biomedical/Medical Engineering.": "1405",
"English Language and Literature, General.": "2301",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Microbiological Sciences and Immunology.": "2605",
"Ecology, Evolution, Systematics, and Population Biology.": "2613",
"Mathematics.": "2701",
"Mathematics.": "2701",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Parks, Recreation and Leisure Facilities Management.": "3103",
"Chemistry.": "4005",
"Psychology, General.": "4201",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Security Science and Technology.": "4304",
"Security Science and Technology.": "4304",
"Social Work.": "4407",
"Social Work.": "4407",
"Public Administration and Social Service Professions, Other.": "4499",
"Political Science and Government.": "4510",
"Dance.": "5003",
"Drama/Theatre Arts and Stagecraft.": "5005",
"Fine and Studio Arts.": "5007",
"Music.": "5009",
"Health and Medical Administrative Services.": "5107",
"Rehabilitation and Therapeutic Professions.": "5123",
"Rehabilitation and Therapeutic Professions.": "5123",
"Rehabilitation and Therapeutic Professions.": "5123",
"Rehabilitation and Therapeutic Professions.": "5123",
"Rehabilitation and Therapeutic Professions.": "5123",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Finance and Financial Management Services.": "5208",
"Marketing.": "5214",
"History.": "5401",
"History.": "5401",
"Natural Resources Conservation and Research.": "0301",
"Area Studies.": "0501",
"Area Studies.": "0501",
"Ethnic, Cultural Minority, Gender, and Group Studies.": "0502",
"Ethnic, Cultural Minority, Gender, and Group Studies.": "0502",
"Communication and Media Studies.": "0901",
"Communication and Media Studies.": "0901",
"Communication and Media Studies.": "0901",
"Journalism.": "0904",
"Journalism.": "0904",
"Radio, Television, and Digital Communication.": "0907",
"Radio, Television, and Digital Communication.": "0907",
"Public Relations, Advertising, and Applied Communication.": "0909",
"Public Relations, Advertising, and Applied Communication.": "0909",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Computer/Information Technology Administration and Management.": "1110",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational/Instructional Media Design.": "1305",
"Educational Assessment, Evaluation, and Research.": "1306",
"Educational Assessment, Evaluation, and Research.": "1306",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Student Counseling and Personnel Services.": "1311",
"Student Counseling and Personnel Services.": "1311",
"Student Counseling and Personnel Services.": "1311",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teaching English or French as a Second or Foreign Language.": "1314",
"Aerospace, Aeronautical and Astronautical Engineering.": "1402",
"Aerospace, Aeronautical and Astronautical Engineering.": "1402",
"Aerospace, Aeronautical and Astronautical Engineering.": "1402",
"Architectural Engineering.": "1404",
"Chemical Engineering.": "1407",
"Chemical Engineering.": "1407",
"Chemical Engineering.": "1407",
"Civil Engineering.": "1408",
"Civil Engineering.": "1408",
"Civil Engineering.": "1408",
"Computer Engineering.": "1409",
"Electrical, Electronics and Communications Engineering.": "1410",
"Electrical, Electronics and Communications Engineering.": "1410",
"Electrical, Electronics and Communications Engineering.": "1410",
"Environmental/Environmental Health Engineering.": "1414",
"Environmental/Environmental Health Engineering.": "1414",
"Materials Engineering": "1418",
"Mechanical Engineering.": "1419",
"Mechanical Engineering.": "1419",
"Mechanical Engineering.": "1419",
"Metallurgical Engineering.": "1420",
"Metallurgical Engineering.": "1420",
"Construction Engineering.": "1433",
"Linguistic, Comparative, and Related Language Studies and Services.": "1601",
"Germanic Languages, Literatures, and Linguistics.": "1605",
"Germanic Languages, Literatures, and Linguistics.": "1605",
"Romance Languages, Literatures, and Linguistics.": "1609",
"Romance Languages, Literatures, and Linguistics.": "1609",
"Romance Languages, Literatures, and Linguistics.": "1609",
"Family and Consumer Sciences/Human Sciences, General.": "1901",
"Family and Consumer Sciences/Human Sciences, General.": "1901",
"Family and Consumer Economics and Related Studies.": "1904",
"Family and Consumer Economics and Related Studies.": "1904",
"Foods, Nutrition, and Related Services.": "1905",
"Foods, Nutrition, and Related Services.": "1905",
"Foods, Nutrition, and Related Services.": "1905",
"Human Development, Family Studies, and Related Services.": "1907",
"Human Development, Family Studies, and Related Services.": "1907",
"Apparel and Textiles.": "1909",
"Law.": "2201",
"Legal Research and Advanced Professional Studies.": "2202",
"Legal Research and Advanced Professional Studies.": "2202",
"English Language and Literature, General.": "2301",
"English Language and Literature, General.": "2301",
"English Language and Literature, General.": "2301",
"Rhetoric and Composition/Writing Studies.": "2313",
"Library Science and Administration.": "2501",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Microbiological Sciences and Immunology.": "2605",
"Ecology, Evolution, Systematics, and Population Biology.": "2613",
"Ecology, Evolution, Systematics, and Population Biology.": "2613",
"Mathematics.": "2701",
"Mathematics.": "2701",
"Mathematics.": "2701",
"Applied Mathematics.": "2703",
"Statistics.": "2705",
"Statistics.": "2705",
"Applied Statistics.": "2706",
"Applied Statistics.": "2706",
"Multi-/Interdisciplinary Studies, General.": "3000",
"Multi-/Interdisciplinary Studies, General.": "3000",
"International/Global Studies.": "3020",
"Health and Physical Education/Fitness.": "3105",
"Health and Physical Education/Fitness.": "3105",
"Health and Physical Education/Fitness.": "3105",
"Philosophy.": "3801",
"Religion/Religious Studies.": "3802",
"Religion/Religious Studies.": "3802",
"Chemistry.": "4005",
"Chemistry.": "4005",
"Chemistry.": "4005",
"Geological and Earth Sciences/Geosciences.": "4006",
"Geological and Earth Sciences/Geosciences.": "4006",
"Geological and Earth Sciences/Geosciences.": "4006",
"Physics.": "4008",
"Physics.": "4008",
"Physics.": "4008",
"Materials Sciences.": "4010",
"Psychology, General.": "4201",
"Psychology, General.": "4201",
"Psychology, General.": "4201",
"Clinical, Counseling and Applied Psychology.": "4228",
"Clinical, Counseling and Applied Psychology.": "4228",
"Clinical, Counseling and Applied Psychology.": "4228",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Public Administration.": "4404",
"Social Work.": "4407",
"Social Work.": "4407",
"Social Work.": "4407",
"Anthropology.": "4502",
"Anthropology.": "4502",
"Anthropology.": "4502",
"Criminology.": "4504",
"Criminology.": "4504",
"Geography and Cartography.": "4507",
"Geography and Cartography.": "4507",
"Geography and Cartography.": "4507",
"International Relations and National Security Studies.": "4509",
"Political Science and Government.": "4510",
"Political Science and Government.": "4510",
"Political Science and Government.": "4510",
"Sociology.": "4511",
"Dance.": "5003",
"Dance.": "5003",
"Design and Applied Arts.": "5004",
"Drama/Theatre Arts and Stagecraft.": "5005",
"Drama/Theatre Arts and Stagecraft.": "5005",
"Fine and Studio Arts.": "5007",
"Fine and Studio Arts.": "5007",
"Music.": "5009",
"Music.": "5009",
"Music.": "5009",
"Communication Disorders Sciences and Services.": "5102",
"Communication Disorders Sciences and Services.": "5102",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Mental and Social Health Services and Allied Professions.": "5115",
"Public Health.": "5122",
"Public Health.": "5122",
"Rehabilitation and Therapeutic Professions.": "5123",
"Dietetics and Clinical Nutrition Services.": "5131",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Health Professions and Related Clinical Sciences, Other.": "5199",
"Health Professions and Related Clinical Sciences, Other.": "5199",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Business/Managerial Economics.": "5206",
"Business/Managerial Economics.": "5206",
"Business/Managerial Economics.": "5206",
"Finance and Financial Management Services.": "5208",
"Finance and Financial Management Services.": "5208",
"Finance and Financial Management Services.": "5208",
"Hospitality Administration/Management.": "5209",
"Hospitality Administration/Management.": "5209",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Management Sciences and Quantitative Methods.": "5213",
"Management Sciences and Quantitative Methods.": "5213",
"Management Sciences and Quantitative Methods.": "5213",
"Marketing.": "5214",
"Marketing.": "5214",
"Marketing.": "5214",
"Taxation.": "5216",
"History.": "5401",
"History.": "5401",
"History.": "5401",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Cosmetology and Related Personal Grooming Services.": "1204",
"Industrial Production Technologies/Technicians.": "1506",
"Industrial Production Technologies/Technicians.": "1506",
"Drafting/Design Engineering Technologies/Technicians.": "1513",
"Drafting/Design Engineering Technologies/Technicians.": "1513",
"Human Development, Family Studies, and Related Services.": "1907",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Electrical/Electronics Maintenance and Repair Technology.": "4701",
"Electrical/Electronics Maintenance and Repair Technology.": "4701",
"Precision Metal Working.": "4805",
"Allied Health and Medical Assisting Services.": "5108",
"Allied Health and Medical Assisting Services.": "5108",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Practical Nursing, Vocational Nursing and Nursing Assistants.": "5139",
"Practical Nursing, Vocational Nursing and Nursing Assistants.": "5139",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Operations Support and Assistant Services.": "5204",
"Business Operations Support and Assistant Services.": "5204",
"Computer and Information Sciences, General.": "1101",
"Special Education and Teaching.": "1310",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Education, Other.": "1399",
"English Language and Literature, General.": "2301",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Biology, General.": "2601",
"Mathematics.": "2701",
"Behavioral Sciences.": "3017",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Health and Physical Education/Fitness.": "3105",
"Religion/Religious Studies.": "3802",
"Religion/Religious Studies.": "3802",
"Chemistry.": "4005",
"Psychology, General.": "4201",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Fire Protection.": "4302",
"Homeland Security.": "4303",
"Social Sciences, General.": "4501",
"Political Science and Government.": "4510",
"Sociology.": "4511",
"Drama/Theatre Arts and Stagecraft.": "5005",
"Fine and Studio Arts.": "5007",
"Health and Medical Administrative Services.": "5107",
"Health Professions and Related Clinical Sciences, Other.": "5199",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Human Resources Management and Services.": "5210",
"Human Resources Management and Services.": "5210",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Business, Management, Marketing, and Related Support Services, Other.": "5299",
"History.": "5401",
"Natural Resources Conservation and Research.": "0301",
"Communication and Media Studies.": "0901",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Computer Science.": "1107",
"Computer Science.": "1107",
"Computer/Information Technology Administration and Management.": "1110",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational/Instructional Media Design.": "1305",
"Educational/Instructional Media Design.": "1305",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Student Counseling and Personnel Services.": "1311",
"Student Counseling and Personnel Services.": "1311",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Linguistic, Comparative, and Related Language Studies and Services.": "1601",
"Romance Languages, Literatures, and Linguistics.": "1609",
"English Language and Literature, General.": "2301",
"Rhetoric and Composition/Writing Studies.": "2313",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Biology, General.": "2601",
"Mathematics.": "2701",
"Multi-/Interdisciplinary Studies, General.": "3000",
"Health and Physical Education/Fitness.": "3105",
"Health and Physical Education/Fitness.": "3105",
"Basic Skills and Developmental/Remedial Education.": "3201",
"Physical Sciences.": "4001",
"Chemistry.": "4005",
"Psychology, General.": "4201",
"Psychology, General.": "4201",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Homeland Security.": "4303",
"Public Administration.": "4404",
"Public Administration.": "4404",
"Public Administration.": "4404",
"Economics.": "4506",
"Economics.": "4506",
"Geography and Cartography.": "4507",
"Geography and Cartography.": "4507",
"Geography and Cartography.": "4507",
"Geography and Cartography.": "4507",
"Political Science and Government.": "4510",
"Political Science and Government.": "4510",
"Political Science and Government.": "4510",
"Sociology.": "4511",
"Sociology.": "4511",
"Fine and Studio Arts.": "5007",
"Fine and Studio Arts.": "5007",
"Fine and Studio Arts.": "5007",
"Communication Disorders Sciences and Services.": "5102",
"Health and Medical Administrative Services.": "5107",
"Clinical/Medical Laboratory Science/Research and Allied Professions.": "5110",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Business/Commerce, General.": "5201",
"Business/Commerce, General.": "5201",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Business/Managerial Economics.": "5206",
"Entrepreneurial and Small Business Operations.": "5207",
"Finance and Financial Management Services.": "5208",
"Human Resources Management and Services.": "5210",
"International Business.": "5211",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Marketing.": "5214",
"History.": "5401",
"Agriculture, General.": "0100",
"Agricultural Business and Management.": "0101",
"Agricultural Business and Management.": "0101",
"Agricultural Production Operations.": "0103",
"Agricultural Production Operations.": "0103",
"Agricultural Production Operations.": "0103",
"Animal Sciences.": "0109",
"Animal Sciences.": "0109",
"Animal Sciences.": "0109",
"Food Science and Technology.": "0110",
"Plant Sciences.": "0111",
"Plant Sciences.": "0111",
"Plant Sciences.": "0111",
"Plant Sciences.": "0111",
"Plant Sciences.": "0111",
"Veterinary Medicine.": "0180",
"Veterinary Biomedical and Clinical Sciences.": "0181",
"Veterinary Biomedical and Clinical Sciences.": "0181",
"Natural Resources Conservation and Research.": "0301",
"Natural Resources Conservation and Research.": "0301",
"Natural Resources Conservation and Research.": "0301",
"Natural Resources Conservation and Research.": "0301",
"Natural Resources Management and Policy.": "0302",
"Forestry.": "0305",
"Forestry.": "0305",
"Forestry.": "0305",
"Wildlife and Wildlands Science and Management.": "0306",
"Architecture.": "0402",
"Architecture.": "0402",
"City/Urban, Community and Regional Planning.": "0403",
"Environmental Design.": "0404",
"Interior Architecture.": "0405",
"Landscape Architecture.": "0406",
"Real Estate Development.": "0410",
"Communication and Media Studies.": "0901",
"Communication and Media Studies.": "0901",
"Journalism.": "0904",
"Radio, Television, and Digital Communication.": "0907",
"Public Relations, Advertising, and Applied Communication.": "0909",
"Computer and Information Sciences, General.": "1101",
"Computer Science.": "1107",
"Computer/Information Technology Administration and Management.": "1110",
"Computer/Information Technology Administration and Management.": "1110",
"Education, General.": "1301",
"Education, General.": "1301",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational Administration and Supervision.": "1304",
"Educational/Instructional Media Design.": "1305",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Special Education and Teaching.": "1310",
"Student Counseling and Personnel Services.": "1311",
"Student Counseling and Personnel Services.": "1311",
"Student Counseling and Personnel Services.": "1311",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Engineering, General.": "1401",
"Aerospace, Aeronautical and Astronautical Engineering.": "1402",
"Aerospace, Aeronautical and Astronautical Engineering.": "1402",
"Aerospace, Aeronautical and Astronautical Engineering.": "1402",
"Architectural Engineering.": "1404",
"Architectural Engineering.": "1404",
"Architectural Engineering.": "1404",
"Architectural Engineering.": "1404",
"Chemical Engineering.": "1407",
"Chemical Engineering.": "1407",
"Chemical Engineering.": "1407",
"Civil Engineering.": "1408",
"Civil Engineering.": "1408",
"Civil Engineering.": "1408",
"Computer Engineering.": "1409",
"Computer Engineering.": "1409",
"Computer Engineering.": "1409",
"Electrical, Electronics and Communications Engineering.": "1410",
"Electrical, Electronics and Communications Engineering.": "1410",
"Electrical, Electronics and Communications Engineering.": "1410",
"Materials Engineering": "1418",
"Materials Engineering": "1418",
"Materials Engineering": "1418",
"Mechanical Engineering.": "1419",
"Mechanical Engineering.": "1419",
"Mechanical Engineering.": "1419",
"Polymer/Plastics Engineering.": "1432",
"Polymer/Plastics Engineering.": "1432",
"Polymer/Plastics Engineering.": "1432",
"Industrial Engineering.": "1435",
"Industrial Engineering.": "1435",
"Industrial Engineering.": "1435",
"Industrial Engineering.": "1435",
"Industrial Engineering.": "1435",
"Biological/Biosystems Engineering.": "1445",
"Biological/Biosystems Engineering.": "1445",
"Biological/Biosystems Engineering.": "1445",
"Engineering, Other.": "1499",
"Engineering-Related Fields.": "1515",
"Germanic Languages, Literatures, and Linguistics.": "1605",
"Romance Languages, Literatures, and Linguistics.": "1609",
"Romance Languages, Literatures, and Linguistics.": "1609",
"Foods, Nutrition, and Related Services.": "1905",
"Human Development, Family Studies, and Related Services.": "1907",
"Human Development, Family Studies, and Related Services.": "1907",
"Human Development, Family Studies, and Related Services.": "1907",
"Apparel and Textiles.": "1909",
"Apparel and Textiles.": "1909",
"Family and Consumer Sciences/Human Sciences, Other.": "1999",
"Non-Professional General Legal Studies (Undergraduate).": "2200",
"English Language and Literature, General.": "2301",
"English Language and Literature, General.": "2301",
"English Language and Literature, General.": "2301",
"Rhetoric and Composition/Writing Studies.": "2313",
"Rhetoric and Composition/Writing Studies.": "2313",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Biology, General.": "2601",
"Microbiological Sciences and Immunology.": "2605",
"Zoology/Animal Biology.": "2607",
"Physiology, Pathology and Related Sciences.": "2609",
"Physiology, Pathology and Related Sciences.": "2609",
"Physiology, Pathology and Related Sciences.": "2609",
"Physiology, Pathology and Related Sciences.": "2609",
"Biotechnology.": "2612",
"Ecology, Evolution, Systematics, and Population Biology.": "2613",
"Neurobiology and Neurosciences.": "2615",
"Mathematics.": "2701",
"Mathematics.": "2701",
"Mathematics.": "2701",
"Applied Mathematics.": "2703",
"Applied Mathematics.": "2703",
"Statistics.": "2705",
"Multi-/Interdisciplinary Studies, General.": "3000",
"Nutrition Sciences.": "3019",
"Nutrition Sciences.": "3019",
"Nutrition Sciences.": "3019",
"Philosophy.": "3801",
"Chemistry.": "4005",
"Chemistry.": "4005",
"Chemistry.": "4005",
"Geological and Earth Sciences/Geosciences.": "4006",
"Geological and Earth Sciences/Geosciences.": "4006",
"Geological and Earth Sciences/Geosciences.": "4006",
"Physics.": "4008",
"Physics.": "4008",
"Physics.": "4008",
"Psychology, General.": "4201",
"Psychology, General.": "4201",
"Psychology, General.": "4201",
"Clinical, Counseling and Applied Psychology.": "4228",
"Clinical, Counseling and Applied Psychology.": "4228",
"Public Administration.": "4404",
"Public Administration.": "4404",
"Public Administration.": "4404",
"Public Administration.": "4404",
"Public Administration.": "4404",
"Social Work.": "4407",
"Social Work.": "4407",
"Anthropology.": "4502",
"Criminology.": "4504",
"Economics.": "4506",
"Economics.": "4506",
"Geography and Cartography.": "4507",
"Geography and Cartography.": "4507",
"Geography and Cartography.": "4507",
"Political Science and Government.": "4510",
"Sociology.": "4511",
"Sociology.": "4511",
"Air Transportation.": "4901",
"Design and Applied Arts.": "5004",
"Design and Applied Arts.": "5004",
"Design and Applied Arts.": "5004",
"Drama/Theatre Arts and Stagecraft.": "5005",
"Fine and Studio Arts.": "5007",
"Music.": "5009",
"Communication Disorders Sciences and Services.": "5102",
"Communication Disorders Sciences and Services.": "5102",
"Communication Disorders Sciences and Services.": "5102",
"Health and Medical Administrative Services.": "5107",
"Clinical/Medical Laboratory Science/Research and Allied Professions.": "5110",
"Pharmacy, Pharmaceutical Sciences, and Administration.": "5120",
"Pharmacy, Pharmaceutical Sciences, and Administration.": "5120",
"Pharmacy, Pharmaceutical Sciences, and Administration.": "5120",
"Pharmacy, Pharmaceutical Sciences, and Administration.": "5120",
"Veterinary Medicine.": "5124",
"Veterinary Biomedical and Clinical Sciences.": "5125",
"Veterinary Biomedical and Clinical Sciences.": "5125",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Business/Managerial Economics.": "5206",
"Business/Managerial Economics.": "5206",
"Business/Managerial Economics.": "5206",
"Finance and Financial Management Services.": "5208",
"Hospitality Administration/Management.": "5209",
"Human Resources Management and Services.": "5210",
"International Business.": "5211",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Management Information Systems and Services.": "5212",
"Management Sciences and Quantitative Methods.": "5213",
"Management Sciences and Quantitative Methods.": "5213",
"Management Sciences and Quantitative Methods.": "5213",
"Marketing.": "5214",
"History.": "5401",
"History.": "5401",
"History.": "5401",
"History.": "5401",
"History.": "5401",
"Natural Resources Conservation and Research.": "0301",
"Architecture and Related Services, Other.": "0499",
"Area Studies.": "0501",
"Communication and Media Studies.": "0901",
"Computer and Information Sciences, General.": "1101",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Engineering, General.": "1401",
"Engineering, Other.": "1499",
"Romance Languages, Literatures, and Linguistics.": "1609",
"English Language and Literature, General.": "2301",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Biology, General.": "2601",
"Mathematics.": "2701",
"Applied Mathematics.": "2703",
"International/Global Studies.": "3020",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Philosophy.": "3801",
"Religion/Religious Studies.": "3802",
"Chemistry.": "4005",
"Physics.": "4008",
"Psychology, General.": "4201",
"Economics.": "4506",
"Political Science and Government.": "4510",
"Sociology.": "4511",
"Social Sciences, Other.": "4599",
"Drama/Theatre Arts and Stagecraft.": "5005",
"Fine and Studio Arts.": "5007",
"Music.": "5009",
"Health Services/Allied Health/Health Sciences, General.": "5100",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"History.": "5401",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Industrial Production Technologies/Technicians.": "1506",
"Industrial Production Technologies/Technicians.": "1506",
"Human Development, Family Studies, and Related Services.": "1907",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Fire Protection.": "4302",
"Fire Protection.": "4302",
"Homeland Security, Law Enforcement, Firefighting and Related Protective Services, Other.": "4399",
"Design and Applied Arts.": "5004",
"Design and Applied Arts.": "5004",
"Music.": "5009",
"Allied Health and Medical Assisting Services.": "5108",
"Allied Health and Medical Assisting Services.": "5108",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Practical Nursing, Vocational Nursing and Nursing Assistants.": "5139",
"Practical Nursing, Vocational Nursing and Nursing Assistants.": "5139",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Business Operations Support and Assistant Services.": "5204",
"Business Operations Support and Assistant Services.": "5204",
"Information Science/Studies.": "1104",
"Information Science/Studies.": "1104",
"Computer/Information Technology Administration and Management.": "1110",
"Legal Support Services.": "2203",
"Legal Support Services.": "2203",
"Theological and Ministerial Studies.": "3906",
"Psychology, General.": "4201",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Public Administration.": "4404",
"Health Services/Allied Health/Health Sciences, General.": "5100",
"Health and Medical Administrative Services.": "5107",
"Health and Medical Administrative Services.": "5107",
"Allied Health and Medical Assisting Services.": "5108",
"Public Health.": "5122",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Computer Software and Media Applications.": "1108",
"Computer Engineering Technologies/Technicians.": "1512",
"Human Development, Family Studies, and Related Services.": "1907",
"Human Development, Family Studies, and Related Services.": "1907",
"Legal Support Services.": "2203",
"Legal Support Services.": "2203",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Vehicle Maintenance and Repair Technologies.": "4706",
"Vehicle Maintenance and Repair Technologies.": "4706",
"Health and Medical Administrative Services.": "5107",
"Allied Health and Medical Assisting Services.": "5108",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Operations Support and Assistant Services.": "5204",
"Business Operations Support and Assistant Services.": "5204",
"Applied Horticulture and Horticultural Business Services.": "0106",
"Applied Horticulture and Horticultural Business Services.": "0106",
"Veterinary/Animal Health Technologies/Technicians.": "0183",
"Graphic Communications.": "1003",
"Graphic Communications.": "1003",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Cosmetology and Related Personal Grooming Services.": "1204",
"Environmental Control Technologies/Technicians.": "1505",
"Industrial Production Technologies/Technicians.": "1506",
"Industrial Production Technologies/Technicians.": "1506",
"Mechanical Engineering Related Technologies/Technicians.": "1508",
"Computer Engineering Technologies/Technicians.": "1512",
"Drafting/Design Engineering Technologies/Technicians.": "1513",
"Drafting/Design Engineering Technologies/Technicians.": "1513",
"Foods, Nutrition, and Related Services.": "1905",
"Human Development, Family Studies, and Related Services.": "1907",
"Legal Support Services.": "2203",
"Legal Support Services.": "2203",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Parks, Recreation and Leisure Facilities Management.": "3103",
"Parks, Recreation and Leisure Facilities Management.": "3103",
"Building/Construction Finishing, Management, and Inspection.": "4604",
"Heavy/Industrial Equipment Maintenance Technologies.": "4703",
"Heavy/Industrial Equipment Maintenance Technologies.": "4703",
"Vehicle Maintenance and Repair Technologies.": "4706",
"Vehicle Maintenance and Repair Technologies.": "4706",
"Mechanic and Repair Technologies/Technicians, Other.": "4799",
"Precision Metal Working.": "4805",
"Woodworking.": "4807",
"Design and Applied Arts.": "5004",
"Design and Applied Arts.": "5004",
"Dental Support Services and Allied Professions.": "5106",
"Dental Support Services and Allied Professions.": "5106",
"Allied Health and Medical Assisting Services.": "5108",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Practical Nursing, Vocational Nursing and Nursing Assistants.": "5139",
"Practical Nursing, Vocational Nursing and Nursing Assistants.": "5139",
"Business Administration, Management and Operations.": "5202",
"Business Operations Support and Assistant Services.": "5204",
"Business Operations Support and Assistant Services.": "5204",
"Hospitality Administration/Management.": "5209",
"Hospitality Administration/Management.": "5209",
"Real Estate.": "5215",
"Agriculture/Veterinary Preparatory Programs.": "0113",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Computer Science.": "1107",
"Curriculum and Instruction.": "1303",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Levels and Methods.": "1312",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Teacher Education and Professional Development, Specific Subject Areas.": "1313",
"Non-Professional General Legal Studies (Undergraduate).": "2200",
"Non-Professional General Legal Studies (Undergraduate).": "2200",
"Law.": "2201",
"English Language and Literature, General.": "2301",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Biology, General.": "2601",
"Biochemistry, Biophysics and Molecular Biology.": "2602",
"Mathematics.": "2701",
"Multi-/Interdisciplinary Studies, General.": "3000",
"Dispute Resolution.": "3028",
"Health and Physical Education/Fitness.": "3105",
"Philosophy and Religious Studies, General.": "3800",
"Philosophy.": "3801",
"Bible/Biblical Studies.": "3902",
"Bible/Biblical Studies.": "3902",
"Bible/Biblical Studies.": "3902",
"Missions/Missionary Studies and Missiology.": "3903",
"Theological and Ministerial Studies.": "3906",
"Theological and Ministerial Studies.": "3906",
"Theological and Ministerial Studies.": "3906",
"Pastoral Counseling and Specialized Ministries.": "3907",
"Pastoral Counseling and Specialized Ministries.": "3907",
"Clinical, Counseling and Applied Psychology.": "4228",
"Psychology, Other.": "4299",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Social Sciences, General.": "4501",
"Drama/Theatre Arts and Stagecraft.": "5005",
"Music.": "5009",
"Communication Disorders Sciences and Services.": "5102",
"Communication Disorders Sciences and Services.": "5102",
"Health/Medical Preparatory Programs.": "5111",
"Mental and Social Health Services and Allied Professions.": "5115",
"Mental and Social Health Services and Allied Professions.": "5115",
"Business/Commerce, General.": "5201",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Human Resources Management and Services.": "5210",
"Human Resources Management and Services.": "5210",
"Management Information Systems and Services.": "5212",
"Management Sciences and Quantitative Methods.": "5213",
"Management Sciences and Quantitative Methods.": "5213",
"History.": "5401",
"Agricultural Production Operations.": "0103",
"Communication, Journalism, and Related Programs, Other.": "0999",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Cosmetology and Related Personal Grooming Services.": "1204",
"Cosmetology and Related Personal Grooming Services.": "1204",
"Civil Engineering Technologies/Technicians.": "1502",
"Civil Engineering Technologies/Technicians.": "1502",
"Electrical Engineering Technologies/Technicians.": "1503",
"Electrical Engineering Technologies/Technicians.": "1503",
"Environmental Control Technologies/Technicians.": "1505",
"Environmental Control Technologies/Technicians.": "1505",
"Industrial Production Technologies/Technicians.": "1506",
"Industrial Production Technologies/Technicians.": "1506",
"Drafting/Design Engineering Technologies/Technicians.": "1513",
"Drafting/Design Engineering Technologies/Technicians.": "1513",
"Human Development, Family Studies, and Related Services.": "1907",
"Human Development, Family Studies, and Related Services.": "1907",
"Legal Support Services.": "2203",
"Legal Support Services.": "2203",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Mason/Masonry.": "4601",
"Carpenters.": "4602",
"Electrical and Power Transmission Installers.": "4603",
"Heavy/Industrial Equipment Maintenance Technologies.": "4703",
"Heavy/Industrial Equipment Maintenance Technologies.": "4703",
"Vehicle Maintenance and Repair Technologies.": "4706",
"Precision Metal Working.": "4805",
"Precision Metal Working.": "4805",
"Health and Medical Administrative Services.": "5107",
"Health and Medical Administrative Services.": "5107",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Clinical/Medical Laboratory Science/Research and Allied Professions.": "5110",
"Mental and Social Health Services and Allied Professions.": "5115",
"Somatic Bodywork and Related Therapeutic Services.": "5135",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Practical Nursing, Vocational Nursing and Nursing Assistants.": "5139",
"Accounting and Related Services.": "5203",
"Accounting and Related Services.": "5203",
"Business Operations Support and Assistant Services.": "5204",
"Business Operations Support and Assistant Services.": "5204",
"General Sales, Merchandising and Related Marketing Operations.": "5218",
"Cosmetology and Related Personal Grooming Services.": "1204",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Cosmetology and Related Personal Grooming Services.": "1204",
"Environmental Control Technologies/Technicians.": "1505",
"Environmental Control Technologies/Technicians.": "1505",
"Mechanical Engineering Related Technologies/Technicians.": "1508",
"Mechanical Engineering Related Technologies/Technicians.": "1508",
"Drafting/Design Engineering Technologies/Technicians.": "1513",
"Drafting/Design Engineering Technologies/Technicians.": "1513",
"Human Development, Family Studies, and Related Services.": "1907",
"Human Development, Family Studies, and Related Services.": "1907",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Nuclear and Industrial Radiologic Technologies/Technicians.": "4102",
"Criminal Justice and Corrections.": "4301",
"Mason/Masonry.": "4601",
"Electrical and Power Transmission Installers.": "4603",
"Electrical and Power Transmission Installers.": "4603",
"Heavy/Industrial Equipment Maintenance Technologies.": "4703",
"Heavy/Industrial Equipment Maintenance Technologies.": "4703",
"Vehicle Maintenance and Repair Technologies.": "4706",
"Precision Metal Working.": "4805",
"Precision Metal Working.": "4805",
"Woodworking.": "4807",
"Allied Health and Medical Assisting Services.": "5108",
"Allied Health and Medical Assisting Services.": "5108",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Practical Nursing, Vocational Nursing and Nursing Assistants.": "5139",
"Business Operations Support and Assistant Services.": "5204",
"Business Operations Support and Assistant Services.": "5204",
"Agricultural Production Operations.": "0103",
"Agricultural Production Operations.": "0103",
"Computer and Information Sciences, General.": "1101",
"Computer and Information Sciences, General.": "1101",
"Cosmetology and Related Personal Grooming Services.": "1204",
"Cosmetology and Related Personal Grooming Services.": "1204",
"Culinary Arts and Related Services.": "1205",
"Culinary Arts and Related Services.": "1205",
"Engineering Technology, General.": "1500",
"Engineering Technology, General.": "1500",
"Environmental Control Technologies/Technicians.": "1505",
"Industrial Production Technologies/Technicians.": "1506",
"Industrial Production Technologies/Technicians.": "1506",
"Drafting/Design Engineering Technologies/Technicians.": "1513",
"Human Development, Family Studies, and Related Services.": "1907",
"Human Development, Family Studies, and Related Services.": "1907",
"Legal Support Services.": "2203",
"Liberal Arts and Sciences, General Studies and Humanities.": "2401",
"Multi/Interdisciplinary Studies, Other.": "3099",
"Criminal Justice and Corrections.": "4301",
"Criminal Justice and Corrections.": "4301",
"Building/Construction Finishing, Management, and Inspection.": "4604",
"Mechanics and Repairers, General.": "4700",
"Electrical/Electronics Maintenance and Repair Technology.": "4701",
"Electrical/Electronics Maintenance and Repair Technology.": "4701",
"Heating, Air Conditioning, Ventilation and Refrigeration Maintenance Technology/Technician (HAC, HACR, HVAC, HVACR).": "4702",
"Vehicle Maintenance and Repair Technologies.": "4706",
"Precision Metal Working.": "4805",
"Precision Metal Working.": "4805",
"Air Transportation.": "4901",
"Air Transportation.": "4901",
"Design and Applied Arts.": "5004",
"Design and Applied Arts.": "5004",
"Dental Support Services and Allied Professions.": "5106",
"Dental Support Services and Allied Professions.": "5106",
"Health and Medical Administrative Services.": "5107",
"Health and Medical Administrative Services.": "5107",
"Allied Health and Medical Assisting Services.": "5108",
"Allied Health and Medical Assisting Services.": "5108",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Allied Health Diagnostic, Intervention, and Treatment Professions.": "5109",
"Clinical/Medical Laboratory Science/Research and Allied Professions.": "5110",
"Clinical/Medical Laboratory Science/Research and Allied Professions.": "5110",
"Mental and Social Health Services and Allied Professions.": "5115",
"Mental and Social Health Services and Allied Professions.": "5115",
"Somatic Bodywork and Related Therapeutic Services.": "5135",
"Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.": "5138",
"Practical Nursing, Vocational Nursing and Nursing Assistants.": "5139",
"Business/Commerce, General.": "5201",
"Business Administration, Management and Operations.": "5202",
"Business Administration, Management and Operations.": "5202",
"Accounting and Related Services.": "5203",
"Business Operations Support and Assistant Services.": "5204",
"Business Operations Support and Assistant Services.": "5204"
}